[package]
name = "animation-spring"
version = "0.1.0"
authors = ["Roberto Saccon <rsaccon@gmail.com>"]
edition = "2018"

[dependencies]
dominator = { path = "../.." }
futures-signals = "0.3.0"
futures-preview = "0.3.0-alpha.9"

[dependencies.stdweb]
version = "0.4.10"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
